### ISSUE TITLE
ld: framework not found CoreServices for architecture arm64

### ISSUE THREAD

**Issue by velochy** [jeduan/cordova-plugin-facebook4#717]
Bug report, for 3.1.0 (3.0.0 does not produce this error).

After adding the plugin to my cordova project and trying to compile the project on MacOS Mojave (10.14) in XCode 9.0.1 with Cordova  8.1.2 and Cordova-Ios 4.5.5 , this error shows up in compiling:
```
ld: framework not found CoreServices for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
As noted before, this issue does not happen for 3.0.0 so reverting to that fixes the acute issue for me. Nevertheless, I would prefer to keep on the latest version as I did before.

I can not unfortunately share my project as it is propertiary (work for a company), but I would be happy to report any other information you might want or need.

**Comment by peterpeterparker** [comment]
Unfortunately I think there is nothing we could do in the plugin, for the following reason: the code of the plugin itself between v3.0.0 and v3.1.0 didn't change at all

What did change is the Facebook SDK from v4.36.0 to v4.37.0, therefore I see the following possibilities

1. A code modification would have been needed in order to be compatible with v4.37.0. But I honestly think that's not the case because

a. I tested the plugin with Xcode v10
b. My app which include v3.1.0 has been thru the App Store verification and is currently in stores
c. I don't get any crash report

2. There is a problem inside the Facebook SDK v4.37.0

3. There might be an incompatibility somewhere in your app but not directly because of that plugin but maybe like a chain of plugin or something

so regarding these

1. if there is a problem with the plugin itself, it's only regarding Xcode 9 since I'm all good with Xcode 10, therefore

a. Try to upgrade Xcode (pay attention to the known Cordova compatibility build problem)
b. PR are welcome

2. You could try to reach out Facebook SDK and open an issue there

3. Googling "ld: framework not found CoreServices for architecture arm64" gives many posts back, notably https://stackoverflow.com/questions/34798741/ld-framework-not-found-stripe-for-architecture-x86-64. Did you try any of these solution

Summarized: I keep this open for a bit, maybe someone will land on this and will give you a hint (at some point will close it) but I really think that this isn't something we could solve inside the plugin. I'm not against being corrected, if it's the case, PR are welcome

**Comment by hikarizm** [comment]
I also fail to build with the same phenomenon.
As you say, it's probably a problem with Facebook SDK.
For reference,  errors it.

```
In file included from /Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/Headers/FBSDKCoreKit.h:22:
/Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/Headers/FBSDKAppEvents.h:33:23: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
FBSDK_EXTERN NSString *const FBSDKAppEventsLoggingResultNotification;
                      ^
/Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/Headers/FBSDKAppEvents.h:33:23: note: insert '_Nullable' if the pointer may be null
FBSDK_EXTERN NSString *const FBSDKAppEventsLoggingResultNotification;
                      ^
                        _Nullable 
/Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/Headers/FBSDKAppEvents.h:33:23: note: insert '_Nonnull' if the pointer should never be null
FBSDK_EXTERN NSString *const FBSDKAppEventsLoggingResultNotification;
```

**Comment by peterpeterparker** [comment]
@hikarizm seems you are not the only one https://stackoverflow.com/questions/51060850/nullability-completeness-warning-since-xcode-9-3

**Comment by schwamic** [comment]
@peterpeterparker I have the same problem as @velochy. Version 3.0.0 is working and 3.1.0 not.

**Comment by clearblood** [comment]
Same problem here, 3.0.0 is working, not 3.1.0,
ionic v3.20.0

**Comment by ThorvaldAagaard** [comment]
Would it be possible to add a configuration ITEM, like on android, where you specify the version of SDK to use, so it is possible to select the 4.36 SDK

**Comment by kurtye** [comment]
same problem here, its possible downgrade facebook SDK ?

**Comment by ThorvaldAagaard** [comment]
Only solution for now is to use version 3.0.0

**Comment by peterpeterparker** [comment]
I've just published cordova-plugin-facebook4@v3.2.0 to nom which includes the last Facebook SDK v4.38.1 for both iOS and Android

Someone could give a try to see if Facebook solves this issue with this new version of their SDK?

**Comment by ThorvaldAagaard** [comment]
I have now tried the version 3.2.0 and is getting the same error as with 3.1.0, switching back to 3.0.0 but ready to test or help with any changes. I can see the android version is looking for 4.38.1 SDK, but where is the reference to the IOS SDK?

**Comment by peterpeterparker** [comment]
@ThorvaldAagaard freak sorry to hear that but thx for the test. I stay on my above first comment then, if someone has more inputs or found the root of the problem, ping me

also I could confirm that I shipped in store my app with the last version of the plugin v3.2.0 and faced no problem

about release notes, I described that in https://github.com/jeduan/cordova-plugin-facebook4/issues/725. The Facebook team released the Facebook SDK for iOS v4.38.1 without any release notes, my guess is that they didn't change anything in comparison to v4.38.0 and that they just wanted to follow the version number of the Fb Android SDK

**Comment by ThorvaldAagaard** [comment]
I am still on Xcode V9.1, so it is probably an inderectly reference to a library, that isn't solved.

I am thinking about adding the FacebookSDK using pods, do you think that might help?

Just one idea i have. In the linker statement are there any reference to CoreServices as I can see none in my linker statement. 

I would expect to see CoreServices here
![image](https://user-images.githubusercontent.com/10560652/48982485-7f5f6200-f0e3-11e8-9041-b682a2499488.png)

Is it present in Your project, when running on Xcode 10?

**Comment by ThorvaldAagaard** [comment]
OK, after digging around I think the issue is that CoreServices is introduced in iOS 12, but iOS 12 is only supported by the beta of Xcode 10 or higher, but I will try

https://github.com/sauravexodus/xcode-9-ios-12-support

I have tried upgrading to Xcode 10, but it requires a never OS than High Sierra, and unfortunately my emulator won't cooperate in this upgrade. I have been thinking on investing in a new mac, so I can run Xcode 10

**Comment by ThorvaldAagaard** [comment]
Sorry for hijacking this thread, but after installing the ios-12 supportfiles, I can't find a way in Xcode to use these files when build. I am only allowed to select these 

![image](https://user-images.githubusercontent.com/10560652/48985790-235d0380-f10c-11e8-9532-fad5a3731907.png)

So I better stay on version 3.0.0 until I can upgrade to Xcode 10

**Comment by ThorvaldAagaard** [comment]
I have upgraded to XCode 10 and that solved the issue. Based on my research the only solution for XCode 9 is to stay on 3.0.0

**Comment by preetluv** [comment]
framework not found CoreServices for architecture x86_64
 i have these issue come in xcode

**Comment by preetluv** [comment]
![Screen Shot 2019-03-15 at 3 36 02 PM](https://user-images.githubusercontent.com/36993377/54424060-181ff900-4738-11e9-9a08-17b9814338b1.png)
framework not found CoreServices for architecture x86_64
i have these issue come in xcode

**Comment by ThorvaldAagaard** [comment]
@preetluv Xcode version?

**Comment by Anujmoglix** [comment]
xcode -9.2

**Comment by Akolbogr** [comment]
Hey guys,
Anyone found a solution or workaround to this:

The following build commands failed:
	CompileC /var/root/Library/Developer/Xcode/DerivedData/Hupaka-hjnavamjuwucxxfncxfqtqctcfkn/Build/Intermediates.noindex/Hupaka.build/Debug-iphonesimulator/Hupaka.build/Objects-normal/x86_64/FacebookConnectPlugin.o /Users/muss/Downloads/iOS/hpk/platforms/ios/Hupaka/Plugins/cordova-plugin-facebook4/FacebookConnectPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Command finished with error code 65: xcodebuild -workspace,Hupaka.xcworkspace,-scheme,Hupaka,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE (2nd generation),build,CONFIGURATION_BUILD_DIR=/Users/muss/Downloads/iOS/hpk/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/muss/Downloads/iOS/hpk/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/muss/Downloads/iOS/hpk/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
[ERROR] An error occurred while running subprocess cordova.

I have spent more than 3 days now trying to get past it.

Thanks in advance.

**Comment by noahcooper** [comment]
This plugin is deprecated. Take a look at `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect.

This issue was logged before the plugin switched to using Cocoapods, so it is now moot.
